image: ubuntu:latest
before_script:
    - apt-get update; apt-get install -y libmysqlclient-dev cmake libsqlite3-dev libleveldb-dev libprotobuf-dev protobuf-compiler libsnappy-dev git cmake make g++
    - git submodule update --init --recursive

test:
    script:
        - mkdir build
        - cd build
        - cmake -DCMAKE_BUILD_TYPE=Debug ..
        - make
        - ctest -G 'soci_.*' --output-on-failure
    stage: test
