language: cpp
before_install:
    - git submodule update --init --recursive
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    - sudo apt-get -qq update
    - sudo apt-get install -y libmysqlclient-dev cmake libsqlite3-dev libleveldb-dev libprotobuf-dev protobuf-compiler
    - sudo apt-get install gcc-5 g++-5 -y
    - export CXX="g++-5" CC="gcc-5"
script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Debug ..
    - make
    - ctest -G 'soci_.*' --output-on-failure
    
