language: cpp
before_install:
    - git submodule update --init --recursive
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    - sudo apt-get -qq update
    - sudo apt-get install -y libmysqlclient-dev cmake libsqlite3-dev 
    - sudo apt-get install gcc-4.9 g++-4.9 -y
    - export CXX="g++-4.9" CC="gcc-4.9"
script:
    - mkdir build
    - cd build
    - cmake ..
    - make
    - ctest -G 'soci_.*' --output-on-failure
    
