language: cpp
before_install:
    - git submodule update --init --recursive
    - sudo apt-get -qq update
    - sudo apt-get install -y libmysqlclient-dev cmake libsqlite3-dev 
script:
    - mkdir build
    - cd build
    - cmake ..
    - make
    - ctest -G 'soci_.*' --output-on-failure
    
